#  Copyright (C) 2026 by Tobias Hoffmann
#  License: MIT | Package: concrete-crack-cnn-vs-vit

name: unet_efficientnetv2_s
encoder_name: tu-tf_efficientnetv2_s
decoder: unet
family: cnn
pretrained: true
num_classes: 1
image_size: 224
