#  Copyright (C) 2026 by Tobias Hoffmann
#  License: MIT | Package: concrete-crack-cnn-vs-vit

name: unet_swin_tiny
encoder_name: tu-swin_tiny_patch4_window7_224
decoder: unet
family: vit
pretrained: true
num_classes: 1
image_size: 224
